### ISSUE TITLE
composer-plugin-api requirement

### ISSUE THREAD

**Issue by stefanheppenheimer** [VIISON/composer-rules-plugin#1]
When running `composer install` for a project, which uses the rules plugin, composer displays the following warning:

> The "viison/composer-rules-plugin" plugin requires composer-plugin-api 1.0.0, this WILL break in the future and it should be fixed ASAP (require ^1.0 for example).

@cjuner Please check.

**Comment by m1pl** [comment]
This was fixed with f2beabcd72254cccca952d770cb65e20487c2584
