### ISSUE TITLE
Incompatible with PHP 5.3

### ISSUE THREAD

**Issue by m1pl** [VIISON/composer-rules-plugin#2]
https://github.com/VIISON/composer-rules-plugin/blob/master/composer.json#L13
This breaks the CI testing for SW4.3.7/PHP5.3, please fix!

**Comment by cjuner** [comment]
Fixed with [version 0.11.0](https://github.com/VIISON/composer-rules-plugin/releases/tag/0.11.0). Note that only the production version is compatible with PHP < 5.4.0, the tests (`require-dev`) still need PHP >= 5.4.0.
